import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions | REIPro",
  description:
    "Terms and Conditions for REIPro — Real Estate Investment Analysis Platform.",
};

export default function TermsAndConditions() {
  const lastUpdated = "June 29, 2026";

  return (
    <main className="min-h-screen bg-background">
      <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
        <h1 className="font-heading text-3xl font-bold text-foreground sm:text-4xl">
          Terms &amp; Conditions
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: {lastUpdated}
        </p>

        <div className="prose mt-10 max-w-none space-y-8 text-foreground/90 leading-relaxed">
          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing and using REIPro (the &quot;Service&quot;),
              available at{" "}
              <strong>realestate-investment-pro.vercel.app</strong>, you
              accept and agree to be bound by these Terms and Conditions
              (&quot;Terms&quot;). If you do not agree to these Terms, you
              must not access or use the Service. These Terms constitute a
              legally binding agreement between you and REIPro
              (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;).
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              2. Description of Service
            </h2>
            <p>
              REIPro is a web-based real estate investment analysis
              platform that provides property analysis tools, financial
              calculations, investment scoring, and data-driven insights.
              The Service includes mortgage calculators, cash flow
              modeling, return-on-investment projections, and AI-assisted
              market analysis.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              3. Disclaimer of Financial Advice
            </h2>
            <p>
              <strong>
                THE SERVICE DOES NOT CONSTITUTE FINANCIAL, INVESTMENT,
                LEGAL, TAX, OR REAL ESTATE ADVICE.
              </strong>{" "}
              All analysis, projections, scores, and recommendations
              generated by REIPro are provided for informational and
              educational purposes only. The Service is a computational
              tool designed to assist with property analysis, not a
              substitute for professional guidance.
            </p>
            <p className="mt-2">
              You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>
                Investment decisions should be made with the assistance of
                qualified financial advisors, real estate professionals,
                and legal counsel
              </li>
              <li>
                Projections and forecasts are based on assumptions that may
                not reflect actual market conditions or future performance
              </li>
              <li>
                Past performance and projected returns do not guarantee
                future results
              </li>
              <li>
                Real estate investments involve significant risk, including
                the potential loss of principal
              </li>
              <li>
                We are not a licensed financial advisor, broker, or real
                estate agent
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              4. User Responsibilities
            </h2>
            <p>By using the Service, you agree to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>
                Provide accurate and complete information when using
                analysis tools
              </li>
              <li>
                Use the Service only for lawful purposes and in accordance
                with these Terms
              </li>
              <li>
                Not attempt to reverse engineer, decompile, or
                disassemble any part of the Service
              </li>
              <li>
                Not use automated systems, bots, or scrapers to access the
                Service without our prior written consent
              </li>
              <li>
                Not interfere with or disrupt the integrity or performance
                of the Service
              </li>
              <li>
                Not transmit any viruses, malware, or other harmful code
              </li>
              <li>
                Independently verify all analysis results before making
                any investment decisions
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              5. Intellectual Property
            </h2>
            <p>
              The Service and its original content, features,
              functionality, design, and source code are owned by REIPro
              and are protected by international copyright, trademark,
              patent, trade secret, and other intellectual property laws.
              You may not reproduce, distribute, modify, create derivative
              works of, publicly display, publicly perform, republish,
              download, store, or transmit any of the material on our
              Service, except as permitted by these Terms.
            </p>
            <p className="mt-2">
              The REIPro name, logo, and all related names, logos, product
              and service names, designs, and slogans are trademarks of
              REIPro. You must not use such marks without our prior written
              permission.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              6. Data Accuracy and Calculations
            </h2>
            <p>
              While we strive to ensure the accuracy of our calculation
              engine and analysis tools, we make no warranty or guarantee
              regarding:
            </p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>
                The accuracy, completeness, or reliability of any
                calculations, projections, or investment scores
              </li>
              <li>
                The applicability of results to specific properties,
                markets, or investment scenarios
              </li>
              <li>
                The accuracy of AI-generated insights or recommendations
              </li>
              <li>
                The timeliness or relevance of any data used in analysis
              </li>
            </ul>
            <p className="mt-2">
              Users are responsible for independently verifying all data,
              assumptions, and results produced by the Service.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              7. AI-Powered Features
            </h2>
            <p>
              Certain features of the Service utilize artificial
              intelligence and machine learning technologies. You
              acknowledge that:
            </p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>
                AI-generated content may not always be accurate, complete,
                or current
              </li>
              <li>
                AI analysis is generated based on the data you provide and
                general real estate investment principles
              </li>
              <li>
                AI recommendations should be treated as supplementary
                information, not definitive guidance
              </li>
              <li>
                We are not liable for any decisions made based on
                AI-generated analysis
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              8. Limitation of Liability
            </h2>
            <p>
              TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO
              EVENT SHALL REIPRO, ITS OFFICERS, DIRECTORS, EMPLOYEES,
              AGENTS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING
              WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR
              OTHER INTANGIBLE LOSSES, RESULTING FROM:
            </p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>
                Your access to, use of, or inability to access or use the
                Service
              </li>
              <li>
                Any investment decisions made based on information provided
                by the Service
              </li>
              <li>
                Any financial losses incurred as a result of relying on
                Service output
              </li>
              <li>
                Any conduct or content of any third party on the Service
              </li>
              <li>
                Any unauthorized access, use, or alteration of your data
              </li>
              <li>
                Any errors, inaccuracies, or omissions in calculations or
                analysis
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              9. Disclaimer of Warranties
            </h2>
            <p>
              THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS
              AVAILABLE&quot; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER
              EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED
              WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
              PURPOSE, NON-INFRINGEMENT, OR COURSE OF PERFORMANCE. WE DO
              NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE,
              OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE
              SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              10. Indemnification
            </h2>
            <p>
              You agree to defend, indemnify, and hold harmless REIPro and
              its officers, directors, employees, agents, and affiliates
              from and against any claims, liabilities, damages,
              judgments, awards, losses, costs, expenses, or fees
              (including reasonable attorneys&apos; fees) arising out of or
              relating to your violation of these Terms or your use of the
              Service, including any investment decisions made based on
              analysis provided by the Service.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              11. Governing Law
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance
              with the laws of the United States, without regard to its
              conflict of law provisions. Any disputes arising under or in
              connection with these Terms shall be subject to the exclusive
              jurisdiction of the courts located within the United States.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              12. Severability
            </h2>
            <p>
              If any provision of these Terms is held to be unenforceable
              or invalid, such provision will be changed and interpreted to
              accomplish the objectives of such provision to the greatest
              extent possible under applicable law, and the remaining
              provisions will continue in full force and effect.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              13. Modification of Terms
            </h2>
            <p>
              We reserve the right, at our sole discretion, to modify or
              replace these Terms at any time. If a revision is material,
              we will provide at least 30 days&apos; notice prior to any
              new terms taking effect. What constitutes a material change
              will be determined at our sole discretion. By continuing to
              access or use our Service after any revisions become
              effective, you agree to be bound by the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              14. Termination
            </h2>
            <p>
              We may terminate or suspend your access to the Service
              immediately, without prior notice or liability, for any
              reason whatsoever, including without limitation if you breach
              these Terms. Upon termination, your right to use the Service
              will cease immediately.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              15. Entire Agreement
            </h2>
            <p>
              These Terms, together with our Privacy Policy, constitute
              the entire agreement between you and REIPro regarding the
              use of the Service, and supersede and replace any prior
              agreements we might have had between us regarding the
              Service.
            </p>
          </section>

          <section>
            <h2 className="font-heading text-xl font-semibold text-foreground">
              16. Contact Us
            </h2>
            <p>
              If you have any questions about these Terms, please contact
              us:
            </p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>
                By email:{" "}
                <a
                  href="mailto:legal@reipro.app"
                  className="text-primary hover:underline"
                >
                  legal@reipro.app
                </a>
              </li>
              <li>
                By visiting the contact section on our website
              </li>
            </ul>
          </section>
        </div>
      </div>
    </main>
  );
}
